import 'package:flutter/material.dart';

final darkTheme = ThemeData(
  brightness: Brightness.dark,
  scaffoldBackgroundColor: const Color(0xFF1A1A1A),
  primaryColor: const Color(0xFFFF8C00),
  fontFamily: 'Poppins',
  colorScheme: const ColorScheme.dark(
    primary: Color(0xFFFF8C00),
    secondary: Color.fromARGB(255, 185, 58, 3),
    surface: Color(0xFF1A1A1A),
    background: Color(0xFF1A1A1A),
    error: Colors.red,
    onPrimary: Colors.white,
    onSecondary: Colors.white,
    onSurface: Colors.white,
    onBackground: Colors.white,
    onError: Colors.white,
  ),
  cardColor: Colors.grey[900]?.withOpacity(0.3),
  dividerColor: Colors.grey[800],
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      fontFamily: 'Poppins',
      color: Colors.white,
      fontSize: 30,
      fontWeight: FontWeight.w700,
      letterSpacing: 0.3,
    ),
    headlineMedium: TextStyle(
      fontFamily: 'Poppins',
      color: Colors.white,
      fontSize: 24,
      fontWeight: FontWeight.w600,
      letterSpacing: 0.2,
    ),
    headlineSmall: TextStyle(
      fontFamily: 'Poppins',
      color: Colors.white,
      fontSize: 20,
      fontWeight: FontWeight.w600,
      letterSpacing: 0.1,
    ),
    titleLarge: TextStyle(
      fontFamily: 'Poppins',
      color: Colors.white,
      fontSize: 18,
      fontWeight: FontWeight.w600,
    ),
    titleMedium: TextStyle(
      fontFamily: 'Poppins',
      color: Colors.white,
      fontSize: 16,
      fontWeight: FontWeight.w500,
    ),
    bodyLarge: TextStyle(
      fontFamily: 'Poppins',
      color: Colors.white,
      fontSize: 16,
      fontWeight: FontWeight.w400,
    ),
    bodyMedium: TextStyle(
      fontFamily: 'Poppins',
      color: Colors.white70,
      fontSize: 14,
      fontWeight: FontWeight.w400,
    ),
    bodySmall: TextStyle(
      fontFamily: 'Poppins',
      color: Colors.white54,
      fontSize: 12,
      fontWeight: FontWeight.w400,
    ),
    labelLarge: TextStyle(
      fontFamily: 'Poppins',
      color: Colors.white,
      fontSize: 14,
      fontWeight: FontWeight.w500,
    ),
  ),
  inputDecorationTheme: InputDecorationTheme(
    filled: true,
    fillColor: Colors.grey[900]?.withOpacity(0.3),
    border: OutlineInputBorder(
      borderRadius: BorderRadius.circular(30),
      borderSide: BorderSide.none,
    ),
    hintStyle: const TextStyle(
      fontFamily: 'Poppins',
      color: Colors.white54,
      fontWeight: FontWeight.w400,
    ),
    contentPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 15),
  ),
  bottomNavigationBarTheme: const BottomNavigationBarThemeData(
    backgroundColor: Colors.transparent,
    selectedItemColor: Color(0xFFFF8C00),
    unselectedItemColor: Colors.grey,
    type: BottomNavigationBarType.fixed,
    elevation: 0,
  ),
  cardTheme: CardTheme(
    color: Colors.grey[900]?.withOpacity(0.3),
    elevation: 0,
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(15),
    ),
  ),
  appBarTheme: const AppBarTheme(
    backgroundColor: Colors.transparent,
    elevation: 0,
    centerTitle: true,
    titleTextStyle: TextStyle(
      fontFamily: 'Poppins',
      color: Color(0xFFFF8C00),
      fontSize: 24,
      fontWeight: FontWeight.w600,
      letterSpacing: 0.5,
    ),
  ),
);
